---
title: "Homework 5"
author: "Mari Sanders"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Problem 1 

```{r}
bday_sim <- function(n) {
  bdays <- sample(1:365, size = n, replace = TRUE) 
  
  duplicate <- length(unique(bdays)) < n
  
  return(duplicate)
}

sim_res <- 
  expand_grid(
    n = 2:50, 
    iter = 1:10000
  ) %>% 
  mutate(res = map_lgl(n, bday_sim)) %>% 
  group_by(n) %>% 
  summarize(prob = mean(res))

sim_res %>% 
  ggplot(aes(x = n, y = prob)) + geom_line()
```

# Problem 2 



```{r}
normal_dist <- function(n, true_mean, sd = 5) {
  sim_data <- rnorm(n = 30, mean = true_mean, sd = 5)
  t_test <- t.test(sim_data)
  results <- broom::tidy(t_test)
  
}

sim_results_df <- 
  expand_grid(
    sample_size = 30,
    true_mean = c(1,2,3,4,5,6),
    iter = 1:5000
  ) %>% 
  mutate(
    estimate_df = map(sample_size, \(x) normal_dist(x,true_mean, sd))) %>% 
      unnest(estimate_df) %>% select(estimate, p.value, true_mean) 

sim_results_df %>% 
  filter(p.value < 0.05) %>% 
  group_by(true_mean) %>% 
  summarize(count = n()) %>% 
  ggplot(aes(x = true_mean, y = count)) + geom_line()

sim_results_df %>% 
  group_by(true_mean) %>% 
  summarize(mean_estimate = mean(estimate, na.rm = TRUE)) %>% 
  ggplot(aes(x = true_mean, y = mean_estimate)) +  geom_line()

sim_results_df %>% 
  filter(p.value < 0.05) %>% 
  group_by(true_mean) %>% 
  summarize(mean_estimate = mean(estimate, na.rm = TRUE)) %>% 
  ggplot(aes(x = true_mean, y = mean_estimate))  + geom_line()
```

# Problem 3 

```{r}
homicide_df <- read_csv("data/homicide-data.csv") %>% 
  unite(city_state, c(city, state), sep = ", ") %>% 
  mutate(result = ifelse(disposition == "Closed without arrest" | disposition == "Open/No arrest", "unsolved", "solved"))
```
Describe the data.

```{r}
homicide_df %>% 
  group_by(city_state, result) %>% 
  summarize(count = n()) %>% 
  pivot_wider(
    names_from = "city_state",
    values_from = count
  ) %>% knitr::kable()
```

Baltimore Homicide Proportion

```{r}
baltimore_homicide <- 
  homicide_df  %>% 
  filter(city_state == "Baltimore, MD") %>% 
  group_by(result) %>% 
  summarize(count = n()) 

unsolved_count <- baltimore_homicide %>% 
  filter(result == "unsolved") %>% 
  pull(count)

total_count <- baltimore_homicide  %>% 
  summarize(total = sum(count)) %>% 
  pull(total)

broom::tidy(prop.test(unsolved_count, total_count)) %>% 
  select(estimate, conf.low, conf.high)
```

Other cities Homicide Proportion

```{r}
city_cases <- 
  homicide_df %>% 
  group_by(city_state, result) %>% 
  summarize(count = n())
city_counts <- city_cases %>%
  pivot_wider(names_from = result, values_from = count, values_fill = 0) %>%
  mutate(
    unsolved_count = unsolved,
    total_count = solved + unsolved
  )


results <- city_counts %>% 
  group_by(city_state) %>% 
  mutate(prop_test = map2(unsolved_count,total_count, \(x,y) prop.test(x = x, n = y )),
         tidy = map(prop_test, broom::tidy)) %>% 
  unnest(tidy) %>% select(city_state, estimate, conf.low, conf.high)

results %>% 
  ggplot(aes(x = fct_reorder(city_state, estimate), y = estimate)) + 
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + 
  labs(
    title = "Proportion of Unsolved Homicides by City",
    x = "City",
    y = "Estimated Proportion of Unsolved Homicides"
  )
```

